---
- name: register couchpotato service with the local consul agent
  consul:
    service_name: couchpotato
    service_port: 5050
    script: "curl http://couchpotato:5050"
    interval: 10s
    tags:
      - prod

- name: register sabnzbd service with the local consul agent
  consul:
    service_name: sabnzbd
    service_port: 8080
    script: "curl http://sabnzbd:8080"
    interval: 10s
    tags:
      - prod

- name: register deluge service with the local consul agent
  consul:
    service_name: transmission
    service_port: 9091
    script: "curl http://transmission:9091"
    interval: 10s
    tags:
      - prod
